// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder():Promise<string>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function Nsis(arg1:string):Promise<void>;

export function Quit():Promise<void>;
